version: "3.8"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - "./db/neo4j/data:/data"
      - "./db/neo4j/logs:/logs"
      - "./db/neo4j/import:/var/lib/neo4j/import"
      - "./db/neo4j/plugins:/plugins"
  timescale:
    image: timescale/timescaledb:latest-pg12
    ports:
      - "5105:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - "./db/timescale:/var/lib/postgresql/data"
      - "./seed.sql:/docker-entrypoint-initdb.d/seed.sql"
